### ISSUE TITLE
Module does not build with Slicer nightly

### ISSUE THREAD

**Issue by sjh26** [KitwareMedical/OsteotomyPlanner#115]
- Module needs to be updated to use new markups (planes specifically)
http://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=Osteo

![image](https://user-images.githubusercontent.com/219043/87965006-129f9500-ca89-11ea-8b76-731df6e9e7ed.png)

Tasks:

- [ ] Remove the Planes module from the extension

- [ ] Replace vtkMRMLMarkupsPlanesNode with [new version](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.cxx) - function calls will be different for the new version

**Comment by sjh26** [comment]
Highly impacted functions:

- Planes are sized / positioned based on the model segment they are associated with: https://github.com/KitwareMedical/OsteotomyPlanner/blob/36f7af4d04d6e121d9dcdab5abb6ec4a834a8982/Planner/qSlicerPlannerModuleWidget.cxx#L999 

-  Model is cut based on origin / normal of cutting plane
 https://github.com/KitwareMedical/OsteotomyPlanner/blob/36f7af4d04d6e121d9dcdab5abb6ec4a834a8982/Planner/qSlicerPlannerModuleWidget.cxx#L1244

**Comment by JEHoctor** [comment]
There is currently no documentation for vtkMRMLMarkupsPlaneNode, so refer to [the source](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Markups/MRML/vtkMRMLMarkupsPlaneNode.h) and [the base class API documentation](https://apidocs.slicer.org/master/classvtkMRMLMarkupsNode.html).

**Comment by JEHoctor** [comment]
Note that the node name _does_ change: vtkMRMLMarkups**Planes**Node becomes vtkMRMLMarkups**Plane**Node.

**Comment by sjh26** [comment]
Closed with https://github.com/KitwareMedical/OsteotomyPlanner/commit/3040507a9c3c551d16d6c5ac9f44ca25b89c0bdc
