### ISSUE TITLE
Replace model hierarchy with Subject Hierarchy

### ISSUE THREAD

**Issue by sjh26** [KitwareMedical/OsteotomyPlanner#116]
The module currently uses the outdated Model Hierarchy, which is deprecated.  It should be replace with subject hierarchy.

- Display widget
- Internal storage of model data

**Comment by JEHoctor** [comment]
Is the "Display widget" change localized to [this directory](https://github.com/KitwareMedical/OsteotomyPlanner/tree/master/Planner/Widgets)?

**Comment by sjh26** [comment]
Somewhat.  The display widget I am referring to is this:
https://github.com/KitwareMedical/OsteotomyPlanner/blob/36f7af4d04d6e121d9dcdab5abb6ec4a834a8982/Planner/Resources/UI/qSlicerPlannerModuleWidget.ui#L24

The directory has the model that is used to control the appearance of the widget (column names and roles, etc).  It needs to be updated to compile with the current Slicer

Instead of qMRMLTreeView, we want to use: https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.h

As is done here:
https://github.com/Slicer/Slicer/blob/1a8a34060e491e659c7edd0dc2a7171ca12278ad/Modules/Loadable/Models/Resources/UI/qSlicerModelsModuleWidget.ui#L99

That has a similar model class to control appearance

**Comment by sjh26** [comment]
Closed with https://github.com/KitwareMedical/OsteotomyPlanner/commit/3040507a9c3c551d16d6c5ac9f44ca25b89c0bdc
