### ISSUE TITLE
Implement cutting functionality

### ISSUE THREAD

**Issue by bpaniagua** [KitwareMedical/OsteotomyPlanner#15]
Split model CLI needs correcting. I suggest looking at the https://github.com/DCBIA-OrthoLab/EasyClip-Extension code.

**Comment by bpaniagua** [comment]
The cutting functionality should have an effect in the model hierarchy, by deleting the cut model and creating two branching models with the two pieces that result from the cutting.

**Comment by sjh26** [comment]
Added in #19
