### ISSUE TITLE
Transform should be rigid?

### ISSUE THREAD

**Issue by sjh26** [KitwareMedical/OsteotomyPlanner#17]
The transform applied through the UI should be restricted to a rigid transform.  I have not seen a straightforward way to implement this restriction.

**Comment by vovythevov** [comment]
Do you mean a transform without scaling ?
You can tweak how you allow the user to interact with the transform with the editor properties: https://github.com/Slicer/Slicer/blob/master/Libs/MRML/Core/vtkMRMLTransformDisplayNode.h#L183, maybe this can help ?

**Comment by sjh26** [comment]
Yes, this works!

Thanks!

**Comment by sjh26** [comment]
Fixed in 5ca134f2ba94183081b2d636d3988e362ee107f9
