### ISSUE TITLE
Bone transform does not apply to plane

### ISSUE THREAD

**Issue by sjh26** [KitwareMedical/OsteotomyPlanner#18]
![planetransform](https://user-images.githubusercontent.com/25040869/27103588-28dd558c-5057-11e7-8804-f05d1bdec7b6.png)

**Comment by sjh26** [comment]
@vovythevov  Is there a way to have the plane markup reference the transform node of its model?

**Comment by vovythevov** [comment]
@sjh26 
I believe that as of now, it's intended that the plane markup is *NOT* modified by the model transform.
However, the planes node is initialized so each model has a plane around it's bounding box. The normal of the plane is along the largest bounding box dimension. That's one plane*S* node with multiple planes inside for each model.

To transform the plane WITH the model, you will need a plane*S* node per model with a single plane inside.
You then need to apply the transform currently applied to that model to the plane*S* node. Note that I do not know if when calling a CLI with the planes node, whether the plane given to the CLI will be transformed or not. I suspect not, but you will have to find out :).

Hope this is clear !
Johan

**Comment by sjh26** [comment]
Fixed in 885950194f5a6f61647d3d1fa9ae5402de820982
