### ISSUE TITLE
Work in the IO aspects of the planner

### ISSUE THREAD

**Issue by bpaniagua** [KitwareMedical/OsteotomyPlanner#2]
Prepare the "inputs" tab
- Loading model hierarchies / saving model hierarchies. Due to the target audience of this tool, we should plan on having "load" and "save" buttons within the GUI. The program should allow to load/save one model hierarchy or one single model at a time.
- Hidding/showing models

**Comment by vovythevov** [comment]
Hiding and showing model is possible:
![image](https://cloud.githubusercontent.com/assets/426898/24767499/259aa0d8-1acd-11e7-8922-4b3b83712123.png)


Loading/saving presents a challenge as no infrastructure exists for loading and saving model hierarchies for now. They are always saved through the scene.
It might be worth exploring adding this capability to Slicer.

**Comment by vovythevov** [comment]
Also, added interface to turn on/off transforms:

**Comment by bpaniagua** [comment]
![mockup](https://cloud.githubusercontent.com/assets/2599368/24769335/222d4912-1ad4-11e7-8998-540631f31a2a.png)

**Comment by sjh26** [comment]
Addressed in 1ab1dc5445e4c683a2e9a8ff868b9d759fd435d5
