### ISSUE TITLE
Work in the graphic aspects of the planner

### ISSUE THREAD

**Issue by bpaniagua** [KitwareMedical/OsteotomyPlanner#3]
"Reference" tab
- Allow loading specific reference models that will be used as visual targets for the transformations
- They will not be affected by the transformations

"Metrics" tab
- Display/update surface area and volume (http://www.vtk.org/doc/nightly/html/classvtkMassProperties.html) of each model within a hierarchy automatically after the state has been modified. 
- Model to model distances ([ICP](https://en.wikipedia.org/wiki/Iterative_closest_point) distances) between the target or targets with each model of the input model hierarchy. [ModelToModelDistance](https://www.slicer.org/wiki/Documentation/Nightly/Extensions/ModelToModelDistance) in Slicer does that.

**Comment by bpaniagua** [comment]
![referencetoolsmockup](https://cloud.githubusercontent.com/assets/2599368/24769388/576534be-1ad4-11e7-8d07-8369ca0efcf0.png)
![referencetoolsfunctionality](https://cloud.githubusercontent.com/assets/2599368/24769389/576650ce-1ad4-11e7-8d46-d4e86f48faba.png)

**Comment by vovythevov** [comment]
Reference tab added with: a85d36f98a9a6109786404c353b7c4b9b349a777, cfb8d88dccb74c732631382b2b3d00c1292835c3 and 62016bbb285df69985b8397b9f8c297cdb67e31d

**Comment by sjh26** [comment]
Added in b66c393bbc24e012931b06f09f231fbbd0ec049c
