### ISSUE TITLE
Work in "actions" tab (1/2) bending tool 

### ISSUE THREAD

**Issue by bpaniagua** [KitwareMedical/OsteotomyPlanner#5]
Implement the bending functionality of the planner. More methodological ideas on how to do that will follow.

**Comment by bpaniagua** [comment]
This needs to happen before meeting in October at CNMC:

- Ideas: 
1. https://lorensen.github.io/VTKExamples/site/Cxx/Meshes/DeformPointSet/
2. Probably better idea would be to provide three fiducial points in the mesh: two stable on the sides and one that is the one that can be moved. When you move the point you record the direction and magnitude of the movement, and propagate the movement setting a gaussian kernel to all points around the center point with a std based on the lateral points.

**Comment by bpaniagua** [comment]
This one should come first, placing three points, two control one adjustable point + slider that determines the amount of bending.

**Comment by sjh26** [comment]
Closed with #58
