### ISSUE TITLE
Prepare extension infrastructure

### ISSUE THREAD

**Issue by bpaniagua** [KitwareMedical/OsteotomyPlanner#6]
Prepare the extension infrastructure for the planner
https://www.slicer.org/wiki/Documentation/Nightly/Developers/ExtensionWizard

**Comment by vovythevov** [comment]
Fixed with https://github.com/KitwareMedical/OsteotomyPlanner/commit/94e8ede6e38cdb5ebcaf89c910c64e6652f07659
